# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pi0MJbXTEnxGi5mh5YLslt706KOb7RB5
"""

import streamlit as st
import tensorflow as tf
import numpy as np
from PIL import Image, ImageOps
from tensorflow.keras.preprocessing.image import img_to_array
from keras.models import load_model
import os

@st.cache_resource
def load_fashion_model():
    model_path = 'saved_fashion.h5'
    if not os.path.exists(model_path):
        st.error(f"Model file not found: {model_path}")
        return None
    model = tf.keras.models.load_model(model_path)
    return model

def import_and_predict(image_data, model):
    size = (28, 28)
    image = ImageOps.grayscale(ImageOps.fit(image_data, size, Image.ANTIALIAS))
    img = np.asarray(image)
    img = img / 255.0
    img_reshape = img[np.newaxis, ..., np.newaxis]
    prediction = model.predict(img_reshape)
    return prediction

model = load_fashion_model()
if model is None:
    st.stop()

st.write("# Fashion Dataset by Espiritu_Castillo")
file = st.file_uploader("Choose a photo from your computer", type=["jpg", "png"])

if file is None:
    st.text("Please upload an image file")
else:
    image = Image.open(file)
    st.image(image, use_column_width=True)

    prediction = import_and_predict(image, model)

    class_names = ['T-shirt', 'Top', 'Pullover', 'Dress', 'Coat', 'Sandal', 'Shirt', 'Sneaker', 'Bag', 'Ankle Boot']
    result_class = np.argmax(prediction)
    result_label = class_names[result_class]
    confidence = prediction[0][result_class]

    st.success(f"Prediction: {result_label} ({confidence:.2%} confidence)")
